"""
Carnatic Raga reference dataset — EXPANDED (60+ ragas).

Semitone offsets from tonic (Sa = 0):

  0  Sa
  1  Ri1 (Suddha Rishabham)
  2  Ri2 / Ga1 (Chatusruti Rishabham / Suddha Gandharam)
  3  Ri3 / Ga2 (Shatsruti Rishabham / Sadharana Gandharam)
  4  Ga3 (Antara Gandharam)
  5  Ma1 (Suddha Madhyamam)
  6  Ma2 (Prati Madhyamam)
  7  Pa  (Panchamam)
  8  Da1 (Suddha Dhaivatam)
  9  Da2 / Ni1 (Chatusruti Dhaivatam / Suddha Nishadam)
  10 Da3 / Ni2 (Shatsruti Dhaivatam / Kaisiki Nishadam)
  11 Ni3 (Kakali Nishadam)
"""

RAGAS = [
    # ── Melakarta Ragas ──────────────────────────────────────────────────
    {
        "name": "Kanakangi",
        "melakarta": 1,
        "arohana": "S R1 G1 M1 P D1 N1 S",
        "avarohana": "S N1 D1 P M1 G1 R1 S",
        "swaras": [0, 1, 2, 5, 7, 8, 9],
        "description": "First melakarta raga — uses the most basic set of swaras.",
        "mood": "Meditative",
        "time": "Night",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Ratnangi",
        "melakarta": 2,
        "arohana": "S R1 G1 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G1 R1 S",
        "swaras": [0, 1, 2, 5, 7, 8, 10],
        "description": "Second melakarta; subtle and introspective.",
        "mood": "Introspective",
        "time": "Night",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Mayamalavagowla",
        "melakarta": 15,
        "arohana": "S R1 G3 M1 P D1 N3 S",
        "avarohana": "S N3 D1 P M1 G3 R1 S",
        "swaras": [0, 1, 4, 5, 7, 8, 11],
        "description": "The foundational raga taught to beginners; bright and devotional.",
        "mood": "Devotional, foundational",
        "time": "Morning",
        "composer": "Purandara Dasa",
        "famous_songs": ["Lambodara Lakumikara"],
        "audio_sample": None,
    },
    {
        "name": "Chakravakam",
        "melakarta": 16,
        "arohana": "S R1 G3 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G3 R1 S",
        "swaras": [0, 1, 4, 5, 7, 9, 10],
        "description": "16th melakarta; gentle and flowing character.",
        "mood": "Gentle, flowing",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["O Rangasayee"],
        "audio_sample": None,
    },
    {
        "name": "Suryakantam",
        "melakarta": 17,
        "arohana": "S R1 G3 M1 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 G3 R1 S",
        "swaras": [0, 1, 4, 5, 7, 9, 11],
        "description": "17th melakarta with R1 and G3 combination; radiant.",
        "mood": "Radiant, warm",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Todi (Hanumatodi)",
        "melakarta": 8,
        "arohana": "S R1 G2 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G2 R1 S",
        "swaras": [0, 1, 3, 5, 7, 8, 10],
        "description": "A deeply emotive, complex raga with characteristic gamakas (oscillations).",
        "mood": "Deep, contemplative",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Kaddanu Variki", "Emani Vegintune"],
        "audio_sample": None,
    },
    {
        "name": "Natakapriya",
        "melakarta": 10,
        "arohana": "S R1 G2 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G2 R1 S",
        "swaras": [0, 1, 3, 5, 7, 9, 10],
        "description": "10th melakarta; lively and theatrical.",
        "mood": "Lively, theatrical",
        "time": "Afternoon",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Kharaharapriya",
        "melakarta": 22,
        "arohana": "S R2 G2 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 9, 10],
        "description": "Equivalent to the Dorian mode; rich janya ecosystem, deeply emotive.",
        "mood": "Emotive, versatile",
        "time": "Afternoon/Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Chakkani Raja", "Rama Ninnu Nammina"],
        "audio_sample": None,
    },
    {
        "name": "Gauri Manohari",
        "melakarta": 23,
        "arohana": "S R2 G2 M1 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 9, 11],
        "description": "23rd melakarta; serene and graceful, named after Goddess Gauri.",
        "mood": "Serene, graceful",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Varunapriya",
        "melakarta": 24,
        "arohana": "S R2 G2 M1 P D3 N3 S",
        "avarohana": "S N3 D3 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 10, 11],
        "description": "24th melakarta raga; D3 gives it an unusual, watery quality.",
        "mood": "Mysterious, fluid",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Shankarabharanam",
        "melakarta": 29,
        "arohana": "S R2 G3 M1 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 11],
        "description": "Equivalent to the Western major scale; grand, majestic and versatile.",
        "mood": "Majestic, joyful",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Sadinchane", "Marakata Manimaya"],
        "audio_sample": None,
    },
    {
        "name": "Naganandhini",
        "melakarta": 30,
        "arohana": "S R2 G3 M1 P D3 N3 S",
        "avarohana": "S N3 D3 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 10, 11],
        "description": "30th melakarta; D3 lends it a snake-like sinuous quality.",
        "mood": "Sinuous, hypnotic",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Yagapriya",
        "melakarta": 31,
        "arohana": "S R3 G3 M1 P D1 N1 S",
        "avarohana": "S N1 D1 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 8, 9],
        "description": "31st melakarta; ritualistic and solemn.",
        "mood": "Solemn, ritualistic",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Ragavardhini",
        "melakarta": 32,
        "arohana": "S R3 G3 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 8, 10],
        "description": "32nd melakarta; expansive and enriching.",
        "mood": "Expansive",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Gangeyabhushani",
        "melakarta": 33,
        "arohana": "S R3 G3 M1 P D1 N3 S",
        "avarohana": "S N3 D1 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 8, 11],
        "description": "33rd melakarta; flowing like the Ganges.",
        "mood": "Flowing, divine",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Vagadheeswari",
        "melakarta": 34,
        "arohana": "S R3 G3 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 9, 10],
        "description": "34th melakarta; dedicated to Saraswati, the goddess of speech.",
        "mood": "Scholarly, refined",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Sulini",
        "melakarta": 35,
        "arohana": "S R3 G3 M1 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 9, 11],
        "description": "35th melakarta; strong and powerful.",
        "mood": "Strong, powerful",
        "time": "Afternoon",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Chalanata",
        "melakarta": 36,
        "arohana": "S R3 G3 M1 P D3 N3 S",
        "avarohana": "S N3 D3 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 10, 11],
        "description": "36th melakarta; last of the Suddha Madhyama chakras.",
        "mood": "Heroic, vigorous",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Salagam",
        "melakarta": 37,
        "arohana": "S R1 G1 M2 P D1 N1 S",
        "avarohana": "S N1 D1 P M2 G1 R1 S",
        "swaras": [0, 1, 2, 6, 7, 8, 9],
        "description": "37th melakarta; first of the Prati Madhyama ragas.",
        "mood": "Contemplative",
        "time": "Night",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Jalarnavam",
        "melakarta": 38,
        "arohana": "S R1 G1 M2 P D1 N2 S",
        "avarohana": "S N2 D1 P M2 G1 R1 S",
        "swaras": [0, 1, 2, 6, 7, 8, 10],
        "description": "38th melakarta; oceanic depth and breadth.",
        "mood": "Oceanic, deep",
        "time": "Night",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Kalyani",
        "melakarta": 65,
        "arohana": "S R2 G3 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M2 G3 R2 S",
        "swaras": [0, 2, 4, 6, 7, 9, 11],
        "description": "The Carnatic Lydian-like scale; expansive and auspicious.",
        "mood": "Auspicious, expansive",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Nidhi Chala Sukhama", "Vandanamu Raghunandana"],
        "audio_sample": None,
    },
    {
        "name": "Mechakalyani",
        "melakarta": 65,
        "arohana": "S R2 G3 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M2 G3 R2 S",
        "swaras": [0, 2, 4, 6, 7, 9, 11],
        "description": "Same as Kalyani (the melakarta); parent of the Kalyani janya ragas.",
        "mood": "Auspicious, complete",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Harikambhoji",
        "melakarta": 28,
        "arohana": "S R2 G3 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 10],
        "description": "28th melakarta; the mixolydian equivalent, warm and popular.",
        "mood": "Warm, popular",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Manasuloni"],
        "audio_sample": None,
    },
    {
        "name": "Natabhairavi",
        "melakarta": 20,
        "arohana": "S R2 G2 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 8, 10],
        "description": "20th melakarta; equivalent to the natural minor scale, poignant.",
        "mood": "Poignant, melancholic",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Palinchu Kamakshi"],
        "audio_sample": None,
    },
    {
        "name": "Kiravani",
        "melakarta": 21,
        "arohana": "S R2 G2 M1 P D1 N3 S",
        "avarohana": "S N3 D1 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 8, 11],
        "description": "21st melakarta; harmonic minor equivalent, dramatic and intense.",
        "mood": "Dramatic, intense",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": ["Sree Venkatesa Suprabhatham (adapted)"],
        "audio_sample": None,
    },
    {
        "name": "Sankarabharanam",
        "melakarta": 29,
        "arohana": "S R2 G3 M1 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 11],
        "description": "Alias for Shankarabharanam — the great ionian equivalent raga.",
        "mood": "Majestic",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Sadinchane"],
        "audio_sample": None,
    },
    # ── Popular Janya Ragas ──────────────────────────────────────────────
    {
        "name": "Mohanam",
        "melakarta": None,
        "arohana": "S R2 G3 P D2 S",
        "avarohana": "S D2 P G3 R2 S",
        "swaras": [0, 2, 4, 7, 9],
        "description": "A pentatonic janya of Shankarabharanam; simple, sweet and universally loved.",
        "mood": "Sweet, uplifting",
        "time": "Any time",
        "composer": "Swati Tirunal",
        "famous_songs": ["Krishnaya Vasudevaya", "Mohana Raga Tillana"],
        "audio_sample": None,
    },
    {
        "name": "Hamsadhwani",
        "melakarta": None,
        "arohana": "S R2 G3 P N3 S",
        "avarohana": "S N3 P G3 R2 S",
        "swaras": [0, 2, 4, 7, 11],
        "description": "Pentatonic; the sound of the swan (hamsa); bright and auspicious.",
        "mood": "Bright, auspicious",
        "time": "Morning",
        "composer": "Ramaswami Dikshitar",
        "famous_songs": ["Vatapi Ganapathim", "Saraswati Namosthuthe"],
        "audio_sample": None,
    },
    {
        "name": "Bhairavi",
        "melakarta": None,
        "arohana": "S R2 G2 M1 P D2 N2 S",
        "avarohana": "S N2 D1 P M1 G2 R1 S",
        "swaras": [0, 1, 2, 3, 5, 7, 8, 9, 10],
        "description": "A versatile janya known for its many compound swaras; deeply emotive.",
        "mood": "Bhakti, emotive",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Balagopala", "Entharo Mahanubhavulu"],
        "audio_sample": None,
    },
    {
        "name": "Abhogi",
        "melakarta": None,
        "arohana": "S R2 G2 M1 D2 S",
        "avarohana": "S D2 M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 9],
        "description": "Pentatonic janya of Kharaharapriya; delicate and contemplative.",
        "mood": "Delicate, introspective",
        "time": "Night",
        "composer": "Tyagaraja",
        "famous_songs": ["Rangapura Vihara"],
        "audio_sample": None,
    },
    {
        "name": "Hindolam",
        "melakarta": None,
        "arohana": "S G2 M1 D1 N2 S",
        "avarohana": "S N2 D1 M1 G2 S",
        "swaras": [0, 3, 5, 8, 10],
        "description": "Pentatonic janya of Natabhairavi; evokes swinging, languid emotion.",
        "mood": "Languid, swinging",
        "time": "Early morning",
        "composer": "Multiple",
        "famous_songs": ["Chintayami", "Swaminatha Paripalaya"],
        "audio_sample": None,
    },
    {
        "name": "Madhyamavati",
        "melakarta": None,
        "arohana": "S R2 M1 P N2 S",
        "avarohana": "S N2 P M1 R2 S",
        "swaras": [0, 2, 5, 7, 10],
        "description": "Pentatonic janya of Kharaharapriya; powerful, often used in folk music.",
        "mood": "Powerful, folk",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Marugelara"],
        "audio_sample": None,
    },
    {
        "name": "Kambhoji",
        "melakarta": None,
        "arohana": "S R2 G3 M1 P D2 S",
        "avarohana": "S N2 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 10],
        "description": "A major janya of Harikambhoji; heroic and majestic.",
        "mood": "Heroic, majestic",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Telisi Rama", "Sarasa Sama Dana"],
        "audio_sample": None,
    },
    {
        "name": "Dwijavanti",
        "melakarta": None,
        "arohana": "S R2 G3 M1 P D2 N3 D2 S",
        "avarohana": "S N3 D2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 4, 5, 7, 9, 11],
        "description": "A compound raga janya; uses both G2 and G3, creating unique texture.",
        "mood": "Varied, interesting",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Nagumomu"],
        "audio_sample": None,
    },
    {
        "name": "Bilahari",
        "melakarta": None,
        "arohana": "S R2 G3 P D2 S",
        "avarohana": "S N3 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 11],
        "description": "Vivid and cheerful; related to Shankarabharanam, N3 only in avarohana.",
        "mood": "Cheerful, bright",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Endaro Mahanubhavulu (evening)"],
        "audio_sample": None,
    },
    {
        "name": "Saranga",
        "melakarta": None,
        "arohana": "S R2 M1 P N2 S",
        "avarohana": "S N2 P M1 R2 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 10],
        "description": "A janya raga full of vakra phrases; used for Saranagati (surrender) themes.",
        "mood": "Supplicating, tender",
        "time": "Afternoon",
        "composer": "Tyagaraja",
        "famous_songs": ["Dudukugala"],
        "audio_sample": None,
    },
    {
        "name": "Sriranjani",
        "melakarta": None,
        "arohana": "S R2 G2 M1 D2 N2 S",
        "avarohana": "S N2 D2 M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 9, 10],
        "description": "A janya of Kharaharapriya without Pa; melancholic and deeply felt.",
        "mood": "Melancholic, introspective",
        "time": "Night",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Sree Saraswathi Devi"],
        "audio_sample": None,
    },
    {
        "name": "Vasanta",
        "melakarta": None,
        "arohana": "S G3 R2 G3 M2 D2 N3 S",
        "avarohana": "S N3 D2 M2 G3 R2 S",
        "swaras": [0, 2, 4, 6, 9, 11],
        "description": "An evocative, springtime raga janya of Kalyani.",
        "mood": "Fresh, springlike",
        "time": "Morning",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Kanden Kanden"],
        "audio_sample": None,
    },
    {
        "name": "Suddha Saveri",
        "melakarta": None,
        "arohana": "S R2 M1 P D2 S",
        "avarohana": "S D2 P M1 R2 S",
        "swaras": [0, 2, 5, 7, 9],
        "description": "A pentatonic janya of Harikambhoji; folksy and simple, evokes rustic charm.",
        "mood": "Folksy",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Koluvamaregada"],
        "audio_sample": None,
    },
    {
        "name": "Anandabhairavi",
        "melakarta": None,
        "arohana": "S G2 R2 G2 M1 P D2 P N2 D2 S",
        "avarohana": "S N2 D2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 9, 10],
        "description": "A janya of Natabhairavi with distinct vakra phrasing; tender and folk-flavored.",
        "mood": "Tender, folk",
        "time": "Evening",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Kapali (adapted)"],
        "audio_sample": None,
    },
    {
        "name": "Saveri",
        "melakarta": None,
        "arohana": "S R1 M1 P D1 S",
        "avarohana": "S N3 D1 P M1 G3 R1 S",
        "swaras": [0, 1, 4, 5, 7, 8, 11],
        "description": "An old and austere raga janya of Mayamalavagowla, used for invocatory pieces.",
        "mood": "Austere, devotional",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Rara Venugopabala"],
        "audio_sample": None,
    },
    {
        "name": "Nilambari",
        "melakarta": None,
        "arohana": "S R2 G2 M1 P N2 S",
        "avarohana": "S N2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 10],
        "description": "The lullaby raga; soothing and tender, traditionally sung at nighttime.",
        "mood": "Soothing, tender",
        "time": "Night",
        "composer": "Multiple",
        "famous_songs": ["Thaye Yashoda", "Neelavarni Nindralo"],
        "audio_sample": None,
    },
    {
        "name": "Arabhi",
        "melakarta": None,
        "arohana": "S R2 M1 P D2 S",
        "avarohana": "S N3 D2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 9, 11],
        "description": "A pentatonic-ascending janya of Shankarabharanam; majestic and bright.",
        "mood": "Majestic, bright",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Sogasuga Mridanga"],
        "audio_sample": None,
    },
    {
        "name": "Varali",
        "melakarta": None,
        "arohana": "S R1 G2 M2 P D1 N2 S",
        "avarohana": "S N2 D1 P M2 G2 R1 S",
        "swaras": [0, 1, 3, 6, 7, 8, 10],
        "description": "A heavy janya raga; uses both komal (flat) Ri and M2, creating unusual intervals.",
        "mood": "Brooding, heavy",
        "time": "Night",
        "composer": "Tyagaraja",
        "famous_songs": ["Sharanu Sharanu", "Ninnukori"],
        "audio_sample": None,
    },
    {
        "name": "Pantuvarali",
        "melakarta": None,
        "arohana": "S R1 G3 M2 P D1 N3 S",
        "avarohana": "S N3 D1 P M2 G3 R1 S",
        "swaras": [0, 1, 4, 6, 7, 8, 11],
        "description": "A janya with both komal Ri and tivra Ma; strikingly unique intervals.",
        "mood": "Unique, distinctive",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Sarasiruha"],
        "audio_sample": None,
    },
    {
        "name": "Suddha Dhanyasi",
        "melakarta": None,
        "arohana": "S G2 M1 P N2 S",
        "avarohana": "S N2 P M1 G2 S",
        "swaras": [0, 3, 5, 7, 10],
        "description": "Pentatonic; a minor-feeling raga with a lilting, sweet quality.",
        "mood": "Sweet, pentatonic",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Enta Vedukonina"],
        "audio_sample": None,
    },
    {
        "name": "Reethigowla",
        "melakarta": None,
        "arohana": "S R1 M1 P N2 S",
        "avarohana": "S N2 P D1 M1 G2 R1 S",
        "swaras": [0, 1, 3, 5, 7, 8, 10],
        "description": "A poignant janya with vakra phrases; deeply Bhakti-laden.",
        "mood": "Poignant, devotional",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Sundari Nee Divya"],
        "audio_sample": None,
    },
    {
        "name": "Yamuna Kalyani",
        "melakarta": None,
        "arohana": "S R2 G3 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M1 M2 G3 R2 S",
        "swaras": [0, 2, 4, 5, 6, 7, 9, 11],
        "description": "Uses both Ma1 and Ma2 (dual madhyama); a beautiful, flowing raga.",
        "mood": "Flowing, beautiful",
        "time": "Evening",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Yamuna Kalyani compositions"],
        "audio_sample": None,
    },
    {
        "name": "Nalinakanthi",
        "melakarta": None,
        "arohana": "S R2 G3 M1 P N2 S",
        "avarohana": "S N2 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 10],
        "description": "A Shadjanta raga without Da; flows smoothly and evokes a lotus pond.",
        "mood": "Serene, floral",
        "time": "Morning",
        "composer": "Muthuswami Dikshitar",
        "famous_songs": ["Nalinakanthi pieces"],
        "audio_sample": None,
    },
    {
        "name": "Huseni",
        "melakarta": None,
        "arohana": "S R2 G2 M1 P D2 N2 S",
        "avarohana": "S N2 D1 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 8, 9, 10],
        "description": "A folk-tinged janya with D1 in avarohana; evokes a wistful, rural feel.",
        "mood": "Wistful, folk",
        "time": "Evening",
        "composer": "Tyagaraja",
        "famous_songs": ["Koluvaiyunnade"],
        "audio_sample": None,
    },
    {
        "name": "Devakriya",
        "melakarta": None,
        "arohana": "S R1 P M1 P D1 N3 S",
        "avarohana": "S N3 D1 P M1 R1 S",
        "swaras": [0, 1, 5, 7, 8, 11],
        "description": "An ancient and austere raga; associated with Vedic recitation.",
        "mood": "Ancient, austere",
        "time": "Dawn",
        "composer": "Muthuswami Dikshitar",
        "famous_songs": ["Devakriya compositions"],
        "audio_sample": None,
    },
    {
        "name": "Devamanohari",
        "melakarta": None,
        "arohana": "S R2 M1 P N3 S",
        "avarohana": "S N3 P D2 P M1 R2 S",
        "swaras": [0, 2, 5, 7, 9, 11],
        "description": "A pleasant janya that captivates the mind like the devas.",
        "mood": "Captivating, pleasant",
        "time": "Evening",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Devamanohari songs"],
        "audio_sample": None,
    },
    {
        "name": "Shanmukhapriya",
        "melakarta": 56,
        "arohana": "S R2 G2 M2 P D1 N2 S",
        "avarohana": "S N2 D1 P M2 G2 R2 S",
        "swaras": [0, 2, 3, 6, 7, 8, 10],
        "description": "56th melakarta; named after Shanmukha (Karthikeya), has an unusual colour.",
        "mood": "Unusual, vibrant",
        "time": "Afternoon",
        "composer": "Govindacharya",
        "famous_songs": ["Shanmukhapriya compositions"],
        "audio_sample": None,
    },
    {
        "name": "Simhendramadhyamam",
        "melakarta": 57,
        "arohana": "S R2 G2 M2 P D1 N3 S",
        "avarohana": "S N3 D1 P M2 G2 R2 S",
        "swaras": [0, 2, 3, 6, 7, 8, 11],
        "description": "57th melakarta; dramatic and powerful.",
        "mood": "Dramatic, powerful",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Hemavati",
        "melakarta": 58,
        "arohana": "S R2 G2 M2 P D2 N2 S",
        "avarohana": "S N2 D2 P M2 G2 R2 S",
        "swaras": [0, 2, 3, 6, 7, 9, 10],
        "description": "58th melakarta; Dorian-like with Ma2, giving a unique ambiguity.",
        "mood": "Ambiguous, subtle",
        "time": "Afternoon",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Dharmavati",
        "melakarta": 59,
        "arohana": "S R2 G2 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M2 G2 R2 S",
        "swaras": [0, 2, 3, 6, 7, 9, 11],
        "description": "59th melakarta; ethereal and righteous.",
        "mood": "Ethereal, righteous",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Neetimati",
        "melakarta": 60,
        "arohana": "S R2 G2 M2 P D3 N3 S",
        "avarohana": "S N3 D3 P M2 G2 R2 S",
        "swaras": [0, 2, 3, 6, 7, 10, 11],
        "description": "60th melakarta; principled and just, uses D3.",
        "mood": "Principled, just",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Kantamani",
        "melakarta": 61,
        "arohana": "S R3 G2 M2 P D1 N1 S",
        "avarohana": "S N1 D1 P M2 G2 R3 S",
        "swaras": [0, 3, 6, 7, 8, 9],
        "description": "61st melakarta; jewel-like clarity.",
        "mood": "Clear, gem-like",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Rishabhapriya",
        "melakarta": 62,
        "arohana": "S R3 G2 M2 P D1 N2 S",
        "avarohana": "S N2 D1 P M2 G2 R3 S",
        "swaras": [0, 3, 6, 7, 8, 10],
        "description": "62nd melakarta; dedicated to the Ri swara, bold and striking.",
        "mood": "Bold, striking",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Latangi",
        "melakarta": 63,
        "arohana": "S R3 G3 M2 P D1 N3 S",
        "avarohana": "S N3 D1 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 8, 11],
        "description": "63rd melakarta; graceful and flowing like a creeper.",
        "mood": "Graceful, flowing",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Vachaspati",
        "melakarta": 64,
        "arohana": "S R2 G3 M2 P D2 N2 S",
        "avarohana": "S N2 D2 P M2 G3 R2 S",
        "swaras": [0, 2, 4, 6, 7, 9, 10],
        "description": "64th melakarta; eloquent and scholarly (Vachaspati = lord of speech).",
        "mood": "Eloquent, scholarly",
        "time": "Afternoon",
        "composer": "Govindacharya",
        "famous_songs": ["Vachaspati compositions"],
        "audio_sample": None,
    },
    {
        "name": "Chitrambari",
        "melakarta": 66,
        "arohana": "S R3 G3 M2 P D2 N2 S",
        "avarohana": "S N2 D2 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 9, 10],
        "description": "66th melakarta; colourful and vivid.",
        "mood": "Vivid, colourful",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Sucharitra",
        "melakarta": 67,
        "arohana": "S R3 G3 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 9, 11],
        "description": "67th melakarta; of good character and virtue.",
        "mood": "Virtuous, good",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Jyotiswarupini",
        "melakarta": 68,
        "arohana": "S R3 G3 M2 P D3 N3 S",
        "avarohana": "S N3 D3 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 10, 11],
        "description": "68th melakarta; luminous like divine light.",
        "mood": "Luminous, divine",
        "time": "Evening",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Dhatuvardhani",
        "melakarta": 69,
        "arohana": "S R3 G3 M2 P D1 N1 S",
        "avarohana": "S N1 D1 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 8, 9],
        "description": "69th melakarta; metallic and resonant.",
        "mood": "Resonant, metallic",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Nasikabhushani",
        "melakarta": 70,
        "arohana": "S R3 G3 M2 P D1 N2 S",
        "avarohana": "S N2 D1 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 8, 10],
        "description": "70th melakarta; associated with the nose ornament and delicate beauty.",
        "mood": "Delicate, beautiful",
        "time": "Morning",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Kosalam",
        "melakarta": 71,
        "arohana": "S R3 G3 M2 P D3 N2 S",
        "avarohana": "S N2 D3 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 10],
        "description": "71st melakarta; associated with the kingdom of Kosala (Rama's land).",
        "mood": "Regal, epic",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Rasikapriya",
        "melakarta": 72,
        "arohana": "S R3 G3 M2 P D3 N3 S",
        "avarohana": "S N3 D3 P M2 G3 R3 S",
        "swaras": [0, 3, 4, 6, 7, 10, 11],
        "description": "72nd and final melakarta; beloved of connoisseurs and rasika.",
        "mood": "Connoisseur's delight",
        "time": "Any time",
        "composer": "Govindacharya",
        "famous_songs": [],
        "audio_sample": None,
    },
    # ── Additional Popular Janya Ragas ───────────────────────────────────
    {
        "name": "Bageshri",
        "melakarta": None,
        "arohana": "S G2 M1 D1 N2 S",
        "avarohana": "S N2 D1 M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 8, 10],
        "description": "A raga of deep yearning; gentle in the night.",
        "mood": "Yearning, gentle",
        "time": "Late night",
        "composer": "Multiple",
        "famous_songs": ["Bageshri songs"],
        "audio_sample": None,
    },
    {
        "name": "Charukesi",
        "melakarta": None,
        "arohana": "S R2 G3 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 7, 8, 10],
        "description": "A janya of Harikambhoji; unusual mixture of tivra G3 and komal D1.",
        "mood": "Pensive, graceful",
        "time": "Afternoon",
        "composer": "Tyagaraja",
        "famous_songs": ["Charukesi compositions"],
        "audio_sample": None,
    },
    {
        "name": "Kanada",
        "melakarta": None,
        "arohana": "S R2 G2 M1 P D2 N2 S",
        "avarohana": "S N2 D2 P M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 7, 9, 10],
        "description": "An ancient and noble raga; close to Kharaharapriya but distinct.",
        "mood": "Noble, ancient",
        "time": "Late night",
        "composer": "Multiple",
        "famous_songs": ["Kanada compositions"],
        "audio_sample": None,
    },
    {
        "name": "Bagesri",
        "melakarta": None,
        "arohana": "S R2 G2 M1 N2 S",
        "avarohana": "S N2 D1 M1 G2 R2 S",
        "swaras": [0, 2, 3, 5, 8, 10],
        "description": "A gentle, tender raga for late night; closely related to Bageshri.",
        "mood": "Gentle, tender",
        "time": "Late night",
        "composer": "Multiple",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Malahari",
        "melakarta": None,
        "arohana": "S R1 M1 P D1 S",
        "avarohana": "S D1 P M1 R1 S",
        "swaras": [0, 1, 5, 7, 8],
        "description": "A pentatonic raga used in Mangala (auspicious) songs and concerts.",
        "mood": "Auspicious, simple",
        "time": "Morning",
        "composer": "Purandara Dasa",
        "famous_songs": ["Shambho Mahadeva"],
        "audio_sample": None,
    },
    {
        "name": "Kokilapriya",
        "melakarta": None,
        "arohana": "S R1 G2 M1 P D1 N1 S",
        "avarohana": "S N1 D1 P M1 G2 R1 S",
        "swaras": [0, 1, 3, 5, 7, 8, 9],
        "description": "The cuckoo's delight; sweet and melodious.",
        "mood": "Sweet, bird-like",
        "time": "Morning",
        "composer": "Multiple",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Nattai",
        "melakarta": None,
        "arohana": "S R3 G3 M1 P N3 S",
        "avarohana": "S N3 P D2 P M1 G3 R3 S",
        "swaras": [0, 3, 4, 5, 7, 9, 11],
        "description": "A brave, audacious raga; often opens concerts.",
        "mood": "Brave, audacious",
        "time": "Any time",
        "composer": "Tyagaraja",
        "famous_songs": ["Nattai compositions"],
        "audio_sample": None,
    },
    {
        "name": "Gowla",
        "melakarta": None,
        "arohana": "S R1 M1 P N3 S",
        "avarohana": "S N3 D1 P M1 G3 R1 S",
        "swaras": [0, 1, 4, 5, 7, 8, 11],
        "description": "An ancient janya; emotive and introspective, related to Mayamalavagowla.",
        "mood": "Introspective, ancient",
        "time": "Morning",
        "composer": "Tyagaraja",
        "famous_songs": ["Gowla compositions"],
        "audio_sample": None,
    },
    {
        "name": "Purvi Kalyani",
        "melakarta": None,
        "arohana": "S R2 G3 M1 M2 P D2 N3 S",
        "avarohana": "S N3 D2 P M2 M1 G3 R2 S",
        "swaras": [0, 2, 4, 5, 6, 7, 9, 11],
        "description": "Uses both Ma1 and Ma2; transitional and beautiful.",
        "mood": "Transitional, twilight",
        "time": "Evening (Sandhya)",
        "composer": "Multiple",
        "famous_songs": [],
        "audio_sample": None,
    },
    {
        "name": "Punnagavarali",
        "melakarta": None,
        "arohana": "S R1 G2 M1 P D1 N2 S",
        "avarohana": "S N2 D1 P M1 G2 R1 S",
        "swaras": [0, 1, 3, 5, 7, 8, 10],
        "description": "A poignant, tender raga; the scent of the punnaga flower at dusk.",
        "mood": "Tender, poignant",
        "time": "Evening",
        "composer": "Papanasam Sivan",
        "famous_songs": ["Punnagavarali pieces"],
        "audio_sample": None,
    },
]

RAGA_INDEX = {r["name"]: r for r in RAGAS}
SWARA_NAMES = ["Sa", "Ri1", "Ri2/Ga1", "Ri3/Ga2", "Ga3", "Ma1", "Ma2", "Pa", "Da1", "Da2/Ni1", "Da3/Ni2", "Ni3"]
